"use client";
import { useState } from "react";
import { SOPOutput } from "@/lib/types";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  HeadingLevel,
  BorderStyle,
  ShadingType,
  convertInchesToTwip,
} from "docx";
import { saveAs } from "file-saver";

interface SOPDocxDownloadProps {
  sop: SOPOutput;
}

const INDIGO_HEX = "4F46E5";
const AMBER_HEX = "D97706";
const SLATE_LIGHT = "F1F5F9";
const EMERALD_HEX = "059669";
const RED_HEX = "DC2626";
const BORDER_COLOR = "CBD5E1";

function makeBorder(color = BORDER_COLOR) {
  return {
    top: { style: BorderStyle.SINGLE, size: 1, color },
    bottom: { style: BorderStyle.SINGLE, size: 1, color },
    left: { style: BorderStyle.SINGLE, size: 1, color },
    right: { style: BorderStyle.SINGLE, size: 1, color },
  };
}

function buildDocx(sop: SOPOutput): Document {
  const children: Paragraph[] | (Paragraph | Table)[] = [];
  const allChildren: (Paragraph | Table)[] = [];

  // ─── Title Page ───
  allChildren.push(
    new Paragraph({ spacing: { after: 600 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        new TextRun({ text: sop.document_title, bold: true, size: 56, color: INDIGO_HEX, font: "Calibri" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Standard Operating Procedure", size: 28, color: "64748B", font: "Calibri" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
      children: [
        new TextRun({ text: `Version ${sop.version}  |  Effective Date: ${sop.effective_date}`, size: 22, color: "94A3B8", font: "Calibri" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Generated by Contextus — Knowledge OS", size: 20, color: "94A3B8", italics: true, font: "Calibri" }),
      ],
    }),
  );

  // ─── Table of Contents ───
  allChildren.push(
    new Paragraph({ spacing: { before: 400 } }),
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
      children: [new TextRun({ text: "Table of Contents", bold: true, color: INDIGO_HEX, font: "Calibri" })],
    }),
  );

  const tocEntries = [
    "1. Purpose & Scope",
    "2. Roles & Responsibilities",
    ...sop.sections.map((s, i) => `${i + 3}. ${s.title}`),
    `${sop.sections.length + 3}. Areas of Opportunity`,
  ];
  if (sop.glossary.length > 0) {
    tocEntries.push(`${sop.sections.length + 4}. Glossary`);
  }
  tocEntries.forEach((entry) => {
    allChildren.push(
      new Paragraph({
        spacing: { after: 80 },
        children: [new TextRun({ text: entry, size: 22, color: "334155", font: "Calibri" })],
      }),
    );
  });

  // ─── 1. Purpose & Scope ───
  allChildren.push(
    new Paragraph({ spacing: { before: 400 } }),
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
      children: [new TextRun({ text: "1. Purpose & Scope", bold: true, color: INDIGO_HEX, font: "Calibri" })],
    }),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { after: 100 },
      children: [new TextRun({ text: "Purpose", bold: true, color: "334155", font: "Calibri" })],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({ text: sop.purpose, size: 22, color: "475569", font: "Calibri" })],
    }),
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { after: 100 },
      children: [new TextRun({ text: "Scope", bold: true, color: "334155", font: "Calibri" })],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [new TextRun({ text: sop.scope, size: 22, color: "475569", font: "Calibri" })],
    }),
  );

  // ─── 2. Roles & Responsibilities ───
  if (sop.roles_responsibilities.length > 0) {
    allChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        children: [new TextRun({ text: "2. Roles & Responsibilities", bold: true, color: INDIGO_HEX, font: "Calibri" })],
      }),
    );

    const headerRow = new TableRow({
      tableHeader: true,
      children: [
        new TableCell({
          width: { size: 30, type: WidthType.PERCENTAGE },
          shading: { type: ShadingType.CLEAR, fill: INDIGO_HEX },
          borders: makeBorder(INDIGO_HEX),
          children: [new Paragraph({ children: [new TextRun({ text: "Role", bold: true, color: "FFFFFF", size: 20, font: "Calibri" })] })],
        }),
        new TableCell({
          width: { size: 70, type: WidthType.PERCENTAGE },
          shading: { type: ShadingType.CLEAR, fill: INDIGO_HEX },
          borders: makeBorder(INDIGO_HEX),
          children: [new Paragraph({ children: [new TextRun({ text: "Responsibilities", bold: true, color: "FFFFFF", size: 20, font: "Calibri" })] })],
        }),
      ],
    });

    const dataRows = sop.roles_responsibilities.map(
      (rr) =>
        new TableRow({
          children: [
            new TableCell({
              borders: makeBorder(),
              children: [new Paragraph({ children: [new TextRun({ text: rr.role, bold: true, size: 20, font: "Calibri" })] })],
            }),
            new TableCell({
              borders: makeBorder(),
              children: rr.responsibilities.map(
                (r) => new Paragraph({ spacing: { after: 40 }, children: [new TextRun({ text: `• ${r}`, size: 20, color: "475569", font: "Calibri" })] }),
              ),
            }),
          ],
        }),
    );

    allChildren.push(
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [headerRow, ...dataRows],
      }),
    );
  }

  // ─── Process Sections ───
  sop.sections.forEach((section, sIdx) => {
    const sectionNum = sIdx + 3;

    allChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 100 },
        children: [new TextRun({ text: `${sectionNum}. ${section.title}`, bold: true, color: INDIGO_HEX, font: "Calibri" })],
      }),
    );

    if (section.purpose) {
      allChildren.push(
        new Paragraph({
          spacing: { after: 80 },
          children: [
            new TextRun({ text: "Purpose: ", bold: true, size: 20, color: "475569", font: "Calibri" }),
            new TextRun({ text: section.purpose, size: 20, color: "475569", font: "Calibri" }),
          ],
        }),
      );
    }

    if (section.scope) {
      allChildren.push(
        new Paragraph({
          spacing: { after: 200 },
          children: [
            new TextRun({ text: "Scope: ", bold: true, size: 20, color: "475569", font: "Calibri" }),
            new TextRun({ text: section.scope, size: 20, color: "475569", font: "Calibri" }),
          ],
        }),
      );
    }

    // Steps
    section.steps.forEach((step) => {
      // Step title
      allChildren.push(
        new Paragraph({
          spacing: { before: 200, after: 80 },
          children: [
            new TextRun({ text: `Step ${step.step_number}: `, bold: true, size: 24, color: INDIGO_HEX, font: "Calibri" }),
            new TextRun({ text: step.title, bold: true, size: 24, color: "1E293B", font: "Calibri" }),
          ],
        }),
      );

      // Role
      if (step.responsible_role) {
        allChildren.push(
          new Paragraph({
            spacing: { after: 60 },
            children: [
              new TextRun({ text: "Responsible: ", bold: true, size: 20, color: "64748B", font: "Calibri" }),
              new TextRun({ text: step.responsible_role, size: 20, color: "3B82F6", font: "Calibri" }),
            ],
          }),
        );
      }

      // Description
      allChildren.push(
        new Paragraph({
          spacing: { after: 100 },
          children: [new TextRun({ text: step.description, size: 20, color: "475569", font: "Calibri" })],
        }),
      );

      // Inputs
      if (step.inputs.length > 0) {
        allChildren.push(
          new Paragraph({
            spacing: { after: 40 },
            children: [new TextRun({ text: "Inputs:", bold: true, size: 20, color: "64748B", font: "Calibri" })],
          }),
        );
        step.inputs.forEach((inp) => {
          allChildren.push(
            new Paragraph({
              indent: { left: convertInchesToTwip(0.3) },
              spacing: { after: 30 },
              children: [new TextRun({ text: `• ${inp}`, size: 20, color: "475569", font: "Calibri" })],
            }),
          );
        });
      }

      // Outputs
      if (step.outputs.length > 0) {
        allChildren.push(
          new Paragraph({
            spacing: { after: 40 },
            children: [new TextRun({ text: "Outputs:", bold: true, size: 20, color: "64748B", font: "Calibri" })],
          }),
        );
        step.outputs.forEach((out) => {
          allChildren.push(
            new Paragraph({
              indent: { left: convertInchesToTwip(0.3) },
              spacing: { after: 30 },
              children: [new TextRun({ text: `• ${out}`, size: 20, color: "475569", font: "Calibri" })],
            }),
          );
        });
      }

      // Tools/Systems
      if (step.tools_systems.length > 0) {
        allChildren.push(
          new Paragraph({
            spacing: { after: 40 },
            children: [new TextRun({ text: "Tools / Systems:", bold: true, size: 20, color: "64748B", font: "Calibri" })],
          }),
        );
        step.tools_systems.forEach((t) => {
          allChildren.push(
            new Paragraph({
              indent: { left: convertInchesToTwip(0.3) },
              spacing: { after: 30 },
              children: [new TextRun({ text: `• ${t}`, size: 20, color: "475569", font: "Calibri" })],
            }),
          );
        });
      }

      // Screenshot placeholder
      if (step.screenshot_description) {
        allChildren.push(
          new Paragraph({ spacing: { before: 100 } }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 40 },
            shading: { type: ShadingType.CLEAR, fill: SLATE_LIGHT },
            border: {
              top: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
              bottom: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
              left: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
              right: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
            },
            children: [new TextRun({ text: "[SCREENSHOT PLACEHOLDER]", bold: true, size: 20, color: "94A3B8", font: "Calibri" })],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 100 },
            shading: { type: ShadingType.CLEAR, fill: SLATE_LIGHT },
            border: {
              top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
              bottom: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
              left: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
              right: { style: BorderStyle.DASHED, size: 2, color: "94A3B8" },
            },
            children: [new TextRun({ text: step.screenshot_description, italics: true, size: 18, color: "64748B", font: "Calibri" })],
          }),
        );
      }

      // Tips / Tribal Knowledge
      if (step.tips_notes.length > 0) {
        allChildren.push(
          new Paragraph({
            spacing: { before: 100, after: 40 },
            shading: { type: ShadingType.CLEAR, fill: "FEF3C7" },
            border: {
              top: { style: BorderStyle.SINGLE, size: 1, color: AMBER_HEX },
              bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
              left: { style: BorderStyle.SINGLE, size: 6, color: AMBER_HEX },
              right: { style: BorderStyle.SINGLE, size: 1, color: AMBER_HEX },
            },
            children: [new TextRun({ text: "Tips & Tribal Knowledge", bold: true, size: 18, color: AMBER_HEX, font: "Calibri" })],
          }),
        );
        step.tips_notes.forEach((tip, idx) => {
          const isLast = idx === step.tips_notes.length - 1;
          allChildren.push(
            new Paragraph({
              spacing: { after: isLast ? 100 : 30 },
              indent: { left: convertInchesToTwip(0.2) },
              shading: { type: ShadingType.CLEAR, fill: "FEF3C7" },
              border: {
                top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                bottom: isLast ? { style: BorderStyle.SINGLE, size: 1, color: AMBER_HEX } : { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
                left: { style: BorderStyle.SINGLE, size: 6, color: AMBER_HEX },
                right: { style: BorderStyle.SINGLE, size: 1, color: AMBER_HEX },
              },
              children: [new TextRun({ text: `▸ ${tip}`, size: 18, color: "92400E", font: "Calibri" })],
            }),
          );
        });
      }
    });

    // Exceptions
    if (section.exceptions.length > 0) {
      allChildren.push(
        new Paragraph({
          spacing: { before: 200, after: 80 },
          children: [new TextRun({ text: "Exception Handling", bold: true, size: 22, color: RED_HEX, font: "Calibri" })],
        }),
      );
      section.exceptions.forEach((exc) => {
        allChildren.push(
          new Paragraph({
            spacing: { after: 40 },
            indent: { left: convertInchesToTwip(0.2) },
            children: [new TextRun({ text: `⚠ ${exc}`, size: 20, color: "991B1B", font: "Calibri" })],
          }),
        );
      });
    }
  });

  // ─── Areas of Opportunity ───
  if (sop.areas_of_opportunity.length > 0) {
    const oppNum = sop.sections.length + 3;
    allChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        children: [new TextRun({ text: `${oppNum}. Areas of Opportunity`, bold: true, color: EMERALD_HEX, font: "Calibri" })],
      }),
    );

    sop.areas_of_opportunity.forEach((opp, i) => {
      allChildren.push(
        new Paragraph({
          spacing: { before: 160, after: 60 },
          children: [
            new TextRun({ text: `${i + 1}. ${opp.title}`, bold: true, size: 22, color: "1E293B", font: "Calibri" }),
            new TextRun({ text: `  [${opp.impact.toUpperCase()} IMPACT]`, bold: true, size: 18, color: opp.impact === "high" ? RED_HEX : opp.impact === "medium" ? AMBER_HEX : EMERALD_HEX, font: "Calibri" }),
          ],
        }),
        new Paragraph({
          spacing: { after: 60 },
          children: [new TextRun({ text: opp.description, size: 20, color: "475569", font: "Calibri" })],
        }),
        new Paragraph({
          spacing: { after: 40 },
          children: [
            new TextRun({ text: "Current State: ", bold: true, size: 20, color: "64748B", font: "Calibri" }),
            new TextRun({ text: opp.current_state, size: 20, color: "475569", font: "Calibri" }),
          ],
        }),
        new Paragraph({
          spacing: { after: 100 },
          children: [
            new TextRun({ text: "Improvement: ", bold: true, size: 20, color: EMERALD_HEX, font: "Calibri" }),
            new TextRun({ text: opp.improvement, size: 20, color: "065F46", font: "Calibri" }),
          ],
        }),
      );
    });
  }

  // ─── Glossary ───
  if (sop.glossary.length > 0) {
    const glossNum = sop.sections.length + 4;
    allChildren.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        children: [new TextRun({ text: `${glossNum}. Glossary`, bold: true, color: INDIGO_HEX, font: "Calibri" })],
      }),
    );

    sop.glossary.forEach((item) => {
      allChildren.push(
        new Paragraph({
          spacing: { after: 60 },
          children: [
            new TextRun({ text: `${item.term}: `, bold: true, size: 20, color: "1E293B", font: "Calibri" }),
            new TextRun({ text: item.definition, size: 20, color: "475569", font: "Calibri" }),
          ],
        }),
      );
    });
  }

  // ─── Footer ───
  allChildren.push(
    new Paragraph({ spacing: { before: 600 } }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({ text: "— End of Document —", size: 20, color: "94A3B8", italics: true, font: "Calibri" }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
      children: [
        new TextRun({ text: "Generated by Contextus — Knowledge OS", size: 18, color: "CBD5E1", font: "Calibri" }),
      ],
    }),
  );

  return new Document({
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
            },
          },
        },
        children: allChildren,
      },
    ],
  });
}

export default function SOPDocxDownload({ sop }: SOPDocxDownloadProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    try {
      const doc = buildDocx(sop);
      const blob = await Packer.toBlob(doc);
      const safeTitle = sop.document_title
        .replace(/[^a-zA-Z0-9\s-]/g, "")
        .replace(/\s+/g, "-")
        .toLowerCase()
        .slice(0, 60);
      saveAs(blob, `sop-${safeTitle || "document"}.docx`);
    } catch (err) {
      console.error("Failed to generate DOCX:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-indigo-600 hover:bg-indigo-700 disabled:bg-indigo-400 text-white rounded-lg transition-colors font-medium"
    >
      {isGenerating ? (
        <>
          <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          Generating...
        </>
      ) : (
        <>
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download .docx
        </>
      )}
    </button>
  );
}
